name: smart_device
description: Creating CyBear Jinni Smart Devices
version: 1.0.7
homepage: https://mysimplehub.com
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Functional programming thingies, let you use multiple return types
  dartz: ^0.10.1
  # Convert enum to string
  enum_to_string: ^2.2.1
  # Allow returning more than one type of object
  equatable: ^2.0.7
  integrations_controller:
    #    git: https://github.com/CyBear-Jinni/cbj_integrations_controller.git
    path: ../../packages/integrations_controller
  # Extremely fast, easy to use, and fully async NoSQL database.
  isar: ^3.1.0+1


dev_dependencies:
  build_runner:

  # Code generator for the Isar Database. Finds classes annotated with @Collection.
  isar_generator: ^3.1.0+1
  # Library for mocks
  mockito: ^5.4.2
  test: ^1.24.9
