name: Dart CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  workflow_dispatch:

env:
  flutter_channel: 'stable' # or: 'dev' or 'beta'
  flutter_version: '3.16.5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}

      - uses: actions/setup-java@v3
        with:
          java-version: '12.x'
          distribution: 'zulu'
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: dart test
