name: Main Branch Formatting CI

on:
  pull_request:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Perform formatting
        run: find . -name "*.dart" ! -path '*/gen/*' ! -name 'injection.config.dart' | tr '\n' ' ' | xargs dart format

      # Perform the commit at the end to make sure tests above don't fail
      - name: Commit formatting changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git diff-index --quiet HEAD || (git commit -m 'Automatic formatting' && git push)  