export enum EntityProperties {
    Undefined = "undefined",
    BlindsSwitchState = "blindsSwitchState",
    BoilerSwitchState = "boilerSwitchState",
    LightSwitchState = "lightSwitchState",
    LightColorTemperature = "lightColorTemperature",
    LightColorHsvColor = "lightColorHsvColor",
    LightBrightness = "lightBrightness",
    PingSwitchState = "pingSwitchState",
    PrinterSwitchState = "printerSwitchState",
    SecurityCameraSuspendState = "securityCameraSuspendState",
    SecurityCameraShutDownState = "securityCameraShutDownState",
    SmartComputerSuspendState = "smartComputerSuspendState",
    SmartComputerShutDownState = "smartComputerShutDownState",
    SmartPlugState = "smartPlugState",
    SmartTvSwitchState = "smartTvSwitchState",
    OpenUrl = "openUrl",
    Skip = "skip",
    Volume = "volume",
    SwitchState = "switchState",
    Speakers = "speekers",
    Color = "color",
    AcSwitchState = "acSwitchState",
    Delay = "delay",
}
