name: cybear_jinni_site
description: Site for CyBear Jinni Smart Home
version: 1.0.0+3

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^2.18.2


flutter:
  # Ensures that the Material Icons font is included with your application.
  uses-material-design: true

  assets:
    - assets/
    - assets/fan_art/
    - assets/fan_art/after_editing/
    - assets/translations/
    - assets/images/

  fonts:
    - family: gidole_regular
      fonts:
        - asset: assets/gidole_regular.ttf

dependencies:
  # Automatically resizes text to fit perfectly within its bounds
  auto_size_text: ^3.0.0
  # Helps implement the BLoC pattern.
  bloc: ^8.1.1
  # Show images from the internet and keep them in the cache directory.
  cached_network_image: ^3.2.3
  # Spotlight Bottom Navigation Bar
  cool_nav: ^0.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  # Internationalization (Easy translations)
  easy_localization: ^3.0.1
  # Widget that can be expanded or collapsed by the user.
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  # Bloc for state management, replace StatefulWidget
  flutter_bloc: ^8.1.2
  # staggered grid view which supports multiple columns with rows of varying sizes.
  flutter_staggered_grid_view: ^0.6.2
  # The Font Awesome Icon pack available as set of Flutter Icons. https://fontawesome.com/
  font_awesome_flutter: ^10.4.0
  # Annotations for freezed
  freezed_annotation: ^2.2.0
  # Service locator
  get_it: ^7.2.0
  # Add hex color codes to your flutter projects
  hexcolor: ^3.0.1
  # Convenient code generator for get_it
  injectable: ^2.1.0
  # Links to your text.
  linkable: ^3.0.1
  # Small, easy to use and extensible logger which prints beautiful logs.
  logger: ^1.2.2
  # Popup that ask for the requested permission
  permission_handler: ^10.2.0
  # Allows you to create a readable responsive UI
  responsive_builder: ^0.6.4
  # Launching a URL in the mobile platform
  url_launcher: ^6.1.10
  # YouTube iFrame player
  youtube_player_iframe: ^4.0.4

dev_dependencies:
  # A build system for Dart code generation and modular compilation.
  build_runner:

  flutter_test:
    sdk: flutter
  # Code generator for unions/pattern-matching/copy.
  freezed: ^2.3.2
  # Convenient code generator for get_it.
  injectable_generator: ^2.1.4
  # Collection of lint rules for Dart and Flutter projects.
  lint: ^2.0.1

