name: Dart CI

on:
  push:
    #    branches: [ master, dev ]
    branches: [ master ]
  pull_request:
    #    branches: [ master, dev ]
    branches: [ master ]
  workflow_dispatch:

env:
  flutter_channel: 'stable'
  flutter_version: '3.27.1'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/app

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}

      - uses: actions/setup-java@v3
        with:
          java-version: '12.x'
          distribution: 'zulu'
      - name: Install dependencies
        run: flutter pub get
      - name: Run Flutter analysis
        run: flutter analyze
      - name: Run tests
        run: flutter test
